Added fonts, images, icons
CSSA-UCSD/conference2023 pull request #9
Opened 2023-04-18 01:32 UTC by llennemann

2023-04-19 21:30 UTC, vchou105 requested changes
I think we are missing the schedule page (purple/pink fuchsia galaxy) and speaker page (black space) backgrounds according to the figma.

2023-04-19 21:30 UTC, vchou105 commented on src/assets/purpleBackground.png
Not sure why the background looks like there are crosses on it but we can fix this later if it looks like an issue after implementing?

2023-04-20 06:30 UTC, llennemann commented on src/assets/purpleBackground.png
For some reason some backgrounds have crosses even though the file on my computer doesn't, but we can fix if it's an issue for sure!

2023-04-20 06:31 UTC, llennemann commented on src/assets/fonts/futura/futur.ttf
Font package has it like that - not too sure if it's intentional or not

2023-04-20 20:08 UTC, vchou105 approved these changes

2023-04-20 21:09 UTC, merged